### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by bmwGTR** [portapps/discord-portable#37]
Hello,

thank you for your work, running fine!
For Discord there is a workaround how to set a proxy for it - is this also possible for Discord portable?
https://www.reddit.com/r/discordapp/comments/b20a0x/method_of_setting_a_proxy_for_discord/

**Comment by crazy-max** [comment]
Hi @bmwGTR, I will take a look on this, thanks for your input.

**Comment by crazy-max** [comment]
@bmwGTR You can use the flag `--proxy-server=http://127.0.0.1:1080` through the `discord-portable.yml` configuration:

```yaml
common:
  disable_log: false
  args: [
    "--proxy-server",
    "http://127.0.0.1:1080"
  ]
  env: {}
  app_path: ""
app:
  cleanup: false
```
